name: build

on:
#  push:
#    branches:
#    - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [MI-R4A, NETGEAR-R7450]
        toolchain: [mipsel-linux-uclibc]
    steps:
      - uses: actions/checkout@main
      - uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ matrix.target }}-${{ matrix.toolchain }}
      - uses: actions/setup-go@main
        with:
          go-version: '1.22'
          check-latest: true
          cache: false
      - uses: actions/setup-node@main
        with:
          node-version: 20
          check-latest: true
      - name: Prepare environment
        run: |
          sudo apt update
          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
      - name: Start build firmware
        run: |
          make ${{ matrix.target }} TOOLCHAIN=${{ matrix.toolchain }}
          echo "TAG_ANME=$(TZ='Asia/Shanghai' date +%Y.%m.%d-%H%M)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.target }}-${{ matrix.toolchain }}
          path: trunk/images/*.trx
      - uses: ncipollo/release-action@main
        with:
          commit: ${{ github.sha }}
          tag: ${{ env.TAG_ANME }}
          artifacts: trunk/images/*.trx
          allowUpdates: true
          omitBodyDuringUpdate: true